@_7.MinimalAPI_HostAddress = http://localhost:5000

GET {{_7.MinimalAPI_HostAddress}}/users
Accept: application/json

###

GET {{_7.MinimalAPI_HostAddress}}/user/4

###

PUT {{_7.MinimalAPI_HostAddress}}/user/2
Content-Type: application/json

{
  "id": 2,
  "name": "Hector New",
  "email": "hector.new@domain.be"
}

###

POST {{_7.MinimalAPI_HostAddress}}/user
Content-Type: application/json

{
  "id": 5,
  "name": "Charlie",
  "email": "charlie@domain.be"
}

###

DELETE {{_7.MinimalAPI_HostAddress}}/user/5

### 

GET {{_7.MinimalAPI_HostAddress}}/tickets

###

GET {{_7.MinimalAPI_HostAddress}}/ticket/1

###

PUT {{_7.MinimalAPI_HostAddress}}/ticket/2
Content-Type: application/json

{
  "id": 2,
  "title": "Outlook crash",
  "description": "Outlook closes instantly after launch.",
  "status": "Fixed!",
  "userId": 2,
  "createdAt": "2025-06-18T09:38:38.2659611+02:00"
}

###

POST {{_7.MinimalAPI_HostAddress}}/ticket
Content-Type: application/json

{
  "id": 4,
  "title": "DeadLine",
  "description": "The software will be finished for 18/06/25 at 17.00 PM",
  "status": "Not finished",
  "userId": 4,
  "createdAt": "2025-06-18T09:48:28.2659611+02:00"
}

###

DELETE {{_7.MinimalAPI_HostAddress}}/ticket/3

###