@_7.MinimalAPI_HostAddress = http://localhost:5000

GET {{_7.MinimalAPI_HostAddress}}/api/User
Accept: application/json

###

GET {{_7.MinimalAPI_HostAddress}}/api/User/2

###

PUT {{_7.MinimalAPI_HostAddress}}/api/User/2
Content-Type: application/json

{
  "id": 2,
  "firstName": "Hector",
  "lastName": "New",
  "email": "hector.new@domain.be"
}

###

POST {{_7.MinimalAPI_HostAddress}}/api/User
Content-Type: application/json

{
  "firstName": "Charlie",
  "lastName": "Alywell",
  "email": "charlie@domain.be"
}

###

DELETE {{_7.MinimalAPI_HostAddress}}/api/User/4

### 

GET {{_7.MinimalAPI_HostAddress}}/api/Ticket

###

GET {{_7.MinimalAPI_HostAddress}}/api/Ticket/3

###

PUT {{_7.MinimalAPI_HostAddress}}/api/Ticket/2
Content-Type: application/json

{
  "id": 2,
  "title": "Outlook crash",
  "description": "Outlook closes instantly after launch.",
  "status": "Fixed",
  "userId": 2,
  "createdAt": "2025-06-18T09:38:38.2659611+02:00"
}

###

POST {{_7.MinimalAPI_HostAddress}}/api/Ticket
Content-Type: application/json

{
  "title": "DeadLine Frontend",
  "description": "The software frontend will be finished for 16/07/25 at 17.00 PM",
  "userId": 2
}

###

POST {{_7.MinimalAPI_HostAddress}}/api/Ticket
Content-Type: application/json

{
  "title": "DeadLine Backend",
  "description": "The software backend will be finished for 18/07/25 at 17.00 PM",
  "userId": 2
}

###

DELETE {{_7.MinimalAPI_HostAddress}}/api/Ticket/1

###